### ISSUE TITLE
Helm version 3.0.0+ not supported by meepctl

### ISSUE THREAD

**Issue by dilallkx** [InterDigitalInc/AdvantEDGE#50]
**Describe the bug**
Snap is configured by default to automatically install updates. Helm version 3.0.0 was released yesterday and automatically installed on my system running AdvantEDGE. This is a major Helm release that is not yet supported by _meepctl_. The impact is that the AdvtantEDGE core & dependency pods can no longer be deleted or deployed.

**To Reproduce**
1. Install Helm v3+
2. Run 'helm ls' and notice that platform deployments are no longer visible
3. Try to delete or deploy core pods 
4. Observer _meepctl_ errors

**Expected behavior**
Helm v3 should be supported by _meepctl_.

**AdvantEDGE versions**
```
$ meepctl version all
Using repo config file: /home/englab/dilallkx/AdvantEDGE/.meepctl-repocfg.yaml
Using meepctl config file: /home/englab/.meepctl.yaml
{
  "name": "meepctl",
  "version": "1.3.0"
}
{
  "name": ".meepctl-repocfg.yaml",
  "version": "1.3.0"
}
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/InterDigitalInc/AdvantEDGE/go-apps/meepctl/cmd.getHelmVersion(0xc88960)
        /home/englab/dilallkx/AdvantEDGE/go-apps/meepctl/cmd/version.go:160 +0x6f8
github.com/InterDigitalInc/AdvantEDGE/go-apps/meepctl/cmd.versionsDep(0xc88960)
        /home/englab/dilallkx/AdvantEDGE/go-apps/meepctl/cmd/version.go:271 +0x2b
github.com/InterDigitalInc/AdvantEDGE/go-apps/meepctl/cmd.glob..func12(0xc88960, 0xc000143140, 0x1, 0x1)
        /home/englab/dilallkx/AdvantEDGE/go-apps/meepctl/cmd/version.go:79 +0x443
github.com/spf13/cobra.(*Command).execute(0xc88960, 0xc000143100, 0x1, 0x1, 0xc88960, 0xc000143100)
        /home/englab/gocode/pkg/mod/github.com/spf13/cobra@v0.0.0-20190109003409-7547e83b2d85/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc88240, 0x0, 0xc88960, 0xc00010bf68)
        /home/englab/gocode/pkg/mod/github.com/spf13/cobra@v0.0.0-20190109003409-7547e83b2d85/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /home/englab/gocode/pkg/mod/github.com/spf13/cobra@v0.0.0-20190109003409-7547e83b2d85/command.go:800
github.com/InterDigitalInc/AdvantEDGE/go-apps/meepctl/cmd.Execute()
        /home/englab/dilallkx/AdvantEDGE/go-apps/meepctl/cmd/root.go:51 +0x41
main.main()
        /home/englab/dilallkx/AdvantEDGE/go-apps/meepctl/main.go:24 +0x20
```

**AdvantEDGE node:**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

$ uname -a
Linux 4.15.0-70-generic #79~16.04.1-Ubuntu SMP Tue Nov 12 14:01:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dilallkx** [comment]
Until Helm v3 support is added, the workaround is to install v2.16 as described in the updated installation procedure [here](https://github.com/InterDigitalInc/AdvantEDGE/wiki/Runtime-environment#step-1---install-helm-details).

In summary, run the command:
```
sudo snap refresh helm --channel=2.16/stable --classic
```

**Comment by dilallkx** [comment]
You may need to run the following command as well to get the matching Tiller version, as described [here](https://github.com/InterDigitalInc/AdvantEDGE/wiki/runtime-environment#step-3---configure-tiller).

```
# Re-initialize Tiller with crb
helm init --service-account tiller --upgrade
```

**Comment by dilallkx** [comment]
Helm v3 support added in release v1.6.0.
